/* SPDX-License-Identifier: MPL-2.0 */
/* SCSI task-tag messages used by imported FreeBSD drivers. */

#ifndef EDGEOS_COMPAT_FREEBSD_CAM_SCSI_SCSI_MESSAGE_H
#define EDGEOS_COMPAT_FREEBSD_CAM_SCSI_SCSI_MESSAGE_H

#define MSG_SIMPLE_Q_TAG 0x20
#define MSG_HEAD_OF_Q_TAG 0x21
#define MSG_ORDERED_Q_TAG 0x22
#define MSG_SIMPLE_TASK MSG_SIMPLE_Q_TAG
#define MSG_HEAD_OF_QUEUE_TASK MSG_HEAD_OF_Q_TAG
#define MSG_ORDERED_TASK MSG_ORDERED_Q_TAG
#define MSG_ACA_TASK 0x24
#define MSG_ABORT_TASK_SET 0x06
#define MSG_NOOP 0x08
#define MSG_TARGET_RESET 0x0c
#define MSG_CLEAR_TASK_SET 0x0e
#define MSG_CLEAR_ACA 0x16
#define MSG_LOGICAL_UNIT_RESET 0x17
#define MSG_EXT_WDTR_BUS_8_BIT 0x00
#define MSG_EXT_WDTR_BUS_16_BIT 0x01
#define MSG_QUERY_TASK_SET 0x101
#define MSG_QUERY_ASYNC_EVENT 0x102

#endif
