/* SPDX-License-Identifier: MPL-2.0 */
#ifndef EDGEOS_TEGRA124_SOCTHERM_BINDING_H
#define EDGEOS_TEGRA124_SOCTHERM_BINDING_H

#define TEGRA124_SOCTHERM_SENSOR_CPU 0
#define TEGRA124_SOCTHERM_SENSOR_MEM 1
#define TEGRA124_SOCTHERM_SENSOR_GPU 2
#define TEGRA124_SOCTHERM_SENSOR_PLLX 3

#endif
