/* SPDX-License-Identifier: MPL-2.0 */
#ifndef EDGEOS_COMPAT_FREEBSD_SYS_CK_H
#define EDGEOS_COMPAT_FREEBSD_SYS_CK_H

#include <sys/queue.h>

#define CK_STAILQ_HEAD STAILQ_HEAD
#define CK_STAILQ_ENTRY STAILQ_ENTRY
#define CK_STAILQ_INIT STAILQ_INIT
#define CK_STAILQ_FIRST STAILQ_FIRST
#define CK_STAILQ_NEXT STAILQ_NEXT
#define CK_STAILQ_INSERT_HEAD STAILQ_INSERT_HEAD
#define CK_STAILQ_INSERT_TAIL STAILQ_INSERT_TAIL
#define CK_STAILQ_REMOVE_HEAD STAILQ_REMOVE_HEAD
#define CK_STAILQ_REMOVE STAILQ_REMOVE
#define CK_STAILQ_FOREACH STAILQ_FOREACH

#define CK_LIST_HEAD LIST_HEAD
#define CK_LIST_ENTRY LIST_ENTRY
#define CK_LIST_INIT LIST_INIT
#define CK_LIST_FIRST LIST_FIRST
#define CK_LIST_NEXT LIST_NEXT
#define CK_LIST_INSERT_HEAD LIST_INSERT_HEAD
#define CK_LIST_REMOVE LIST_REMOVE
#define CK_LIST_FOREACH LIST_FOREACH

#define CK_SLIST_HEAD SLIST_HEAD
#define CK_SLIST_ENTRY SLIST_ENTRY
#define CK_SLIST_INIT SLIST_INIT
#define CK_SLIST_FIRST SLIST_FIRST
#define CK_SLIST_NEXT SLIST_NEXT
#define CK_SLIST_INSERT_HEAD SLIST_INSERT_HEAD
#define CK_SLIST_REMOVE_HEAD SLIST_REMOVE_HEAD
#define CK_SLIST_REMOVE SLIST_REMOVE
#define CK_SLIST_FOREACH SLIST_FOREACH

#endif
