#!/usr/bin/env python3
"""Generate MII PHY identifier definitions from the FreeBSD miidevs database."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

from manifest import ManifestError


SYMBOL_PATTERN = re.compile(r"^[A-Za-z0-9_]+$")


@dataclass(frozen=True)
class MiiOui:
    symbol: str
    identifier: int
    name: str


@dataclass(frozen=True)
class MiiModel:
    oui: str
    symbol: str
    identifier: int
    name: str


def _validate_symbol(value: str, line_number: int) -> str:
    if not SYMBOL_PATTERN.fullmatch(value):
        raise ManifestError(
            f"miidevs line {line_number} has invalid symbol {value}"
        )
    return value


def _parse_identifier(
    value: str, line_number: int, maximum: int, field: str
) -> int:
    try:
        identifier = int(value, 0)
    except ValueError as exc:
        raise ManifestError(
            f"miidevs line {line_number} has invalid {field} {value}"
        ) from exc
    if identifier < 0 or identifier > maximum:
        raise ManifestError(
            f"miidevs line {line_number} {field} is outside "
            f"0..0x{maximum:x}"
        )
    return identifier


def _description(fields: list[str]) -> str:
    if "#" not in fields:
        return " ".join(fields)
    comment = fields.index("#")
    primary = " ".join(fields[:comment])
    suffix = " ".join(fields[comment + 1:])
    if not suffix:
        return primary
    return f"{primary} ({suffix})" if primary else f"({suffix})"


def parse_miidevs(source: Path) -> tuple[list[MiiOui], list[MiiModel]]:
    ouis: list[MiiOui] = []
    models: list[MiiModel] = []
    oui_symbols: dict[str, MiiOui] = {}
    model_symbols: dict[tuple[str, str], MiiModel] = {}

    try:
        lines = source.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        raise ManifestError(f"cannot read MII database {source}: {exc}") from exc

    for line_number, raw_line in enumerate(lines, start=1):
        line = raw_line.strip()
        if not line or line.startswith(("#", "/*", "*", "*/")):
            continue
        fields = line.split()
        if fields[0] == "oui":
            if len(fields) < 4:
                raise ManifestError(
                    f"miidevs line {line_number} has an incomplete OUI"
                )
            symbol = _validate_symbol(fields[1], line_number)
            oui = MiiOui(
                symbol,
                _parse_identifier(fields[2], line_number, 0xFFFFFF, "OUI"),
                _description(fields[3:]),
            )
            previous = oui_symbols.get(symbol)
            if previous is not None and previous.identifier != oui.identifier:
                raise ManifestError(
                    f"miidevs line {line_number} conflicts with OUI {symbol}"
                )
            if previous is None:
                oui_symbols[symbol] = oui
                ouis.append(oui)
        elif fields[0] == "model":
            if len(fields) < 5:
                raise ManifestError(
                    f"miidevs line {line_number} has an incomplete model"
                )
            oui_symbol = _validate_symbol(fields[1], line_number)
            symbol = _validate_symbol(fields[2], line_number)
            model = MiiModel(
                oui_symbol,
                symbol,
                _parse_identifier(fields[3], line_number, 0xFFFF, "model"),
                _description(fields[4:]),
            )
            key = (oui_symbol, symbol)
            previous = model_symbols.get(key)
            if previous is not None and previous.identifier != model.identifier:
                raise ManifestError(
                    f"miidevs line {line_number} conflicts with model "
                    f"{oui_symbol}_{symbol}"
                )
            if previous is None:
                model_symbols[key] = model
                models.append(model)

    missing_ouis = sorted({model.oui for model in models} - set(oui_symbols))
    if missing_ouis:
        raise ManifestError(
            "miidevs models reference missing OUIs: " + ", ".join(missing_ouis)
        )
    if not ouis or not models:
        raise ManifestError("miidevs database must contain OUIs and models")
    return ouis, models


def _c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_miidevs_header(ouis: list[MiiOui], models: list[MiiModel]) -> str:
    lines = [
        "/* Generated by tools/bsd_bridge/generate_miidevs.py. */",
        "/* Do not edit this file by hand. */",
        "#ifndef EDGEOS_GENERATED_MIIDEVS_H",
        "#define EDGEOS_GENERATED_MIIDEVS_H",
        "",
    ]
    lines.extend(
        f"#define MII_OUI_{oui.symbol} 0x{oui.identifier:06x}"
        for oui in ouis
    )
    lines.append("")
    for model in models:
        lines.extend(
            [
                f"#define MII_MODEL_{model.oui}_{model.symbol} "
                f"0x{model.identifier:x}",
                f"#define MII_STR_{model.oui}_{model.symbol} "
                f"{_c_string(model.name)}",
            ]
        )
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def generate_miidevs_header(source: Path, output: Path) -> list[Path]:
    ouis, models = parse_miidevs(source)
    output.mkdir(parents=True, exist_ok=True)
    header = output / "miidevs.h"
    header.write_text(render_miidevs_header(ouis, models), encoding="utf-8")
    return [header]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()
    try:
        generated = generate_miidevs_header(
            arguments.source.resolve(), arguments.output.resolve()
        )
    except (ManifestError, OSError) as exc:
        print(f"bsd-miidevs-generation: FAIL: {exc}")
        return 1
    print(f"bsd-miidevs-generation: PASS: generated {len(generated)} file")
    for path in generated:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
