#!/usr/bin/env python3
"""Generate USB identifier headers from the FreeBSD usbdevs database."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

from manifest import ManifestError


SYMBOL_PATTERN = re.compile(r"^[A-Za-z0-9_]+$")


@dataclass(frozen=True)
class UsbVendor:
    symbol: str
    identifier: int
    name: str


@dataclass(frozen=True)
class UsbProduct:
    vendor: str
    symbol: str
    identifier: int
    name: str


def _parse_identifier(value: str, line_number: int) -> int:
    try:
        identifier = int(value, 0)
    except ValueError as exc:
        raise ManifestError(
            f"usbdevs line {line_number} has invalid identifier {value}"
        ) from exc
    if identifier < 0 or identifier > 0xFFFF:
        raise ManifestError(
            f"usbdevs line {line_number} identifier is outside 16 bits"
        )
    return identifier


def _validate_symbol(value: str, line_number: int) -> str:
    if not SYMBOL_PATTERN.fullmatch(value):
        raise ManifestError(
            f"usbdevs line {line_number} has invalid symbol {value}"
        )
    return value


def parse_usbdevs(source: Path) -> tuple[list[UsbVendor], list[UsbProduct]]:
    vendors: list[UsbVendor] = []
    products: list[UsbProduct] = []
    vendor_symbols: dict[str, UsbVendor] = {}
    product_symbols: dict[tuple[str, str], UsbProduct] = {}

    try:
        lines = source.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        raise ManifestError(f"cannot read USB database {source}: {exc}") from exc

    for line_number, raw_line in enumerate(lines, start=1):
        line = raw_line.strip()
        if not line or line.startswith(("#", "/*", "*", "*/")):
            continue
        fields = line.split()
        if fields[0] == "vendor":
            if len(fields) < 4:
                raise ManifestError(
                    f"usbdevs line {line_number} has an incomplete vendor"
                )
            symbol = _validate_symbol(fields[1], line_number)
            vendor = UsbVendor(
                symbol,
                _parse_identifier(fields[2], line_number),
                " ".join(fields[3:]),
            )
            previous_vendor = vendor_symbols.get(symbol)
            if (
                previous_vendor is not None
                and previous_vendor.identifier != vendor.identifier
            ):
                raise ManifestError(
                    f"usbdevs line {line_number} conflicts with vendor {symbol}"
                )
            if previous_vendor is None:
                vendor_symbols[symbol] = vendor
                vendors.append(vendor)
        elif fields[0] == "product":
            if len(fields) < 4:
                raise ManifestError(
                    f"usbdevs line {line_number} has an incomplete product"
                )
            vendor = _validate_symbol(fields[1], line_number)
            symbol = _validate_symbol(fields[2], line_number)
            key = (vendor, symbol)
            product = UsbProduct(
                vendor,
                symbol,
                _parse_identifier(fields[3], line_number),
                " ".join(fields[4:]),
            )
            previous_product = product_symbols.get(key)
            if (
                previous_product is not None
                and previous_product.identifier != product.identifier
            ):
                raise ManifestError(
                    f"usbdevs line {line_number} conflicts with product "
                    f"{vendor}_{symbol}"
                )
            if previous_product is None:
                product_symbols[key] = product
                products.append(product)

    missing_vendors = sorted(
        {product.vendor for product in products} - set(vendor_symbols)
    )
    if missing_vendors:
        raise ManifestError(
            "usbdevs products reference missing vendors: "
            + ", ".join(missing_vendors)
        )
    if not vendors or not products:
        raise ManifestError("usbdevs database must contain vendors and products")
    return vendors, products


def _c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_usbdevs_header(
    vendors: list[UsbVendor], products: list[UsbProduct]
) -> str:
    lines = [
        "/* Generated by tools/bsd_bridge/generate_usbdevs.py. */",
        "/* Do not edit this file by hand. */",
        "#ifndef EDGEOS_GENERATED_USBDEVS_H",
        "#define EDGEOS_GENERATED_USBDEVS_H",
        "",
    ]
    lines.extend(
        f"#define USB_VENDOR_{vendor.symbol} 0x{vendor.identifier:04x}"
        for vendor in vendors
    )
    lines.append("")
    lines.extend(
        f"#define USB_PRODUCT_{product.vendor}_{product.symbol} "
        f"0x{product.identifier:04x}"
        for product in products
    )
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def render_usbdevs_data_header(
    vendors: list[UsbVendor], products: list[UsbProduct]
) -> str:
    vendor_by_symbol = {vendor.symbol: vendor for vendor in vendors}
    lines = [
        "/* Generated by tools/bsd_bridge/generate_usbdevs.py. */",
        "/* Do not edit this file by hand. */",
        "",
        "const struct usb_knowndev usb_knowndevs[] = {",
    ]
    for product in products:
        vendor = vendor_by_symbol[product.vendor]
        lines.extend(
            [
                "    {",
                f"        USB_VENDOR_{product.vendor},",
                f"        USB_PRODUCT_{product.vendor}_{product.symbol},",
                "        0,",
                f"        {_c_string(vendor.name)},",
                f"        {_c_string(product.name)},",
                "    },",
            ]
        )
    for vendor in vendors:
        lines.extend(
            [
                "    {",
                f"        USB_VENDOR_{vendor.symbol},",
                "        0,",
                "        USB_KNOWNDEV_NOPROD,",
                f"        {_c_string(vendor.name)},",
                "        NULL,",
                "    },",
            ]
        )
    lines.extend(["    { 0, 0, 0, NULL, NULL },", "};", ""])
    return "\n".join(lines)


def generate_usbdevs_headers(source: Path, output: Path) -> list[Path]:
    vendors, products = parse_usbdevs(source)
    output.mkdir(parents=True, exist_ok=True)
    header = output / "usbdevs.h"
    data_header = output / "usbdevs_data.h"
    header.write_text(
        render_usbdevs_header(vendors, products), encoding="utf-8"
    )
    data_header.write_text(
        render_usbdevs_data_header(vendors, products), encoding="utf-8"
    )
    return [header, data_header]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()
    try:
        generated = generate_usbdevs_headers(
            arguments.source.resolve(), arguments.output.resolve()
        )
    except (ManifestError, OSError) as exc:
        print(f"bsd-usbdevs-generation: FAIL: {exc}")
        return 1
    print(f"bsd-usbdevs-generation: PASS: generated {len(generated)} files")
    for path in generated:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
