#!/usr/bin/env python3
"""Generate the built-in BSD driver package registry from manifests."""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

from catalog import load_catalog
from manifest import ManifestError, locate_repo_root


def _c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render_package_registry(
    manifest_dir: Path,
    capability_dir: Path,
) -> str:
    """Return a deterministic C package registry."""

    catalog = load_catalog(manifest_dir, capability_dir)
    lines = [
        "/* Generated by tools/bsd_bridge/generate_package_registry.py. */",
        "/* Do not edit this file by hand. */",
        "",
        "#include <stddef.h>",
        "",
        '#include "compat/freebsd/edgeos/package.h"',
        "",
        "bsd_driver_package_record_t bsd_driver_package_registry[] = {",
    ]

    for manifest in sorted(catalog["manifests"], key=lambda item: item["id"]):
        if manifest["package_type"] != "driver":
            continue
        builtin_modules = sum(
            module["build"]["mode"] == "builtin"
            for module in manifest["modules"]
        )
        loadable_modules = sum(
            module["build"]["mode"] == "module"
            for module in manifest["modules"]
        )
        disabled_modules = (
            len(manifest["modules"]) - builtin_modules - loadable_modules
        )
        source_count = sum(
            len(module["sources"]) for module in manifest["modules"]
        )
        initial_state = (
            "BSD_DRIVER_PACKAGE_REGISTERED"
            if builtin_modules or loadable_modules
            else "BSD_DRIVER_PACKAGE_DISABLED"
        )
        lines.extend([
            "    {",
            "        .descriptor = {",
            f"            .id = {_c_string(manifest['id'])},",
            f"            .provider = {_c_string(manifest['provider'])},",
            "            .upstream_commit = "
            f"{_c_string(manifest['upstream']['commit'])},",
            f"            .source_count = {source_count},",
            f"            .builtin_module_count = {builtin_modules},",
            f"            .loadable_module_count = {loadable_modules},",
            f"            .disabled_module_count = {disabled_modules},",
            "        },",
            f"        .state = {initial_state},",
            "        .error = 0,",
            "    },",
        ])

    lines.extend([
        "};",
        "",
        "const size_t bsd_driver_package_registry_count =",
        "    sizeof(bsd_driver_package_registry) /",
        "    sizeof(bsd_driver_package_registry[0]);",
        "",
    ])
    return "\n".join(lines)


def write_registry(path: Path, content: str) -> None:
    """Atomically replace a generated package registry."""

    path = path.resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest-dir",
        type=Path,
        default=Path("config/bsd_drivers/manifests"),
    )
    parser.add_argument(
        "--capability-dir",
        type=Path,
        default=Path("config/bsd_drivers/capabilities"),
    )
    parser.add_argument("--repo-root", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", type=Path)
    arguments = parser.parse_args()

    try:
        repo_root = (
            arguments.repo_root.resolve()
            if arguments.repo_root
            else locate_repo_root(Path.cwd())
        )
        content = render_package_registry(
            (repo_root / arguments.manifest_dir).resolve()
            if not arguments.manifest_dir.is_absolute()
            else arguments.manifest_dir.resolve(),
            (repo_root / arguments.capability_dir).resolve()
            if not arguments.capability_dir.is_absolute()
            else arguments.capability_dir.resolve(),
        )
        if arguments.check is not None:
            check_path = arguments.check.resolve()
            if check_path.read_text(encoding="utf-8") != content:
                raise ManifestError(
                    f"generated package registry is stale: {check_path}"
                )
        elif arguments.output is not None:
            write_registry(arguments.output, content)
        else:
            sys.stdout.write(content)
    except (ManifestError, OSError) as exc:
        print(f"bsd-package-registry: FAIL: {exc}", file=sys.stderr)
        return 1

    action = "checked" if arguments.check else "generated"
    print(f"bsd-package-registry: PASS: {action}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
