/* SPDX-License-Identifier: MPL-2.0 */
/* Btrfs on-disk constants used by the architecture-neutral reader. */

#ifndef EDGEOS_BTRFS_FORMAT_H
#define EDGEOS_BTRFS_FORMAT_H

#define EDGE_BTRFS_SUPER_OFFSET             65536u
#define EDGE_BTRFS_SUPER_SIZE               4096u
#define EDGE_BTRFS_SUPER_MAGIC_OFFSET       0x40u
#define EDGE_BTRFS_SUPER_ROOT_OFFSET        0x50u
#define EDGE_BTRFS_SUPER_CHUNK_ROOT_OFFSET  0x58u
#define EDGE_BTRFS_SUPER_TOTAL_BYTES_OFFSET 0x70u
#define EDGE_BTRFS_SUPER_BYTES_USED_OFFSET  0x78u
#define EDGE_BTRFS_SUPER_SECTOR_SIZE_OFFSET 0x90u
#define EDGE_BTRFS_SUPER_NODE_SIZE_OFFSET   0x94u
#define EDGE_BTRFS_SUPER_SYS_SIZE_OFFSET    0xa0u
#define EDGE_BTRFS_SUPER_COMPAT_RO_OFFSET   0xb4u
#define EDGE_BTRFS_SUPER_INCOMPAT_OFFSET    0xbcu
#define EDGE_BTRFS_SUPER_CSUM_TYPE_OFFSET   0xc4u
#define EDGE_BTRFS_SUPER_ROOT_LEVEL_OFFSET  0xc6u
#define EDGE_BTRFS_SUPER_CHUNK_LEVEL_OFFSET 0xc7u
#define EDGE_BTRFS_SUPER_SYS_ARRAY_OFFSET   0x32bu

#define EDGE_BTRFS_HEADER_ITEMS_OFFSET      96u
#define EDGE_BTRFS_HEADER_LEVEL_OFFSET      100u
#define EDGE_BTRFS_HEADER_SIZE              101u
#define EDGE_BTRFS_LEAF_ITEM_SIZE           25u
#define EDGE_BTRFS_KEY_POINTER_SIZE         33u
#define EDGE_BTRFS_KEY_SIZE                 17u

#define EDGE_BTRFS_ROOT_TREE_OBJECTID       1u
#define EDGE_BTRFS_CHUNK_TREE_OBJECTID      3u
#define EDGE_BTRFS_FS_TREE_OBJECTID         5u
#define EDGE_BTRFS_FIRST_CHUNK_OBJECTID     256u
#define EDGE_BTRFS_FIRST_FREE_OBJECTID      256u

#define EDGE_BTRFS_INODE_ITEM_KEY           1u
#define EDGE_BTRFS_DIR_ITEM_KEY             84u
#define EDGE_BTRFS_DIR_INDEX_KEY            96u
#define EDGE_BTRFS_EXTENT_DATA_KEY          108u
#define EDGE_BTRFS_ROOT_ITEM_KEY            132u
#define EDGE_BTRFS_CHUNK_ITEM_KEY           228u

#define EDGE_BTRFS_FILE_EXTENT_INLINE       0u
#define EDGE_BTRFS_FILE_EXTENT_REGULAR      1u
#define EDGE_BTRFS_FILE_EXTENT_PREALLOC     2u

#define EDGE_BTRFS_BLOCK_GROUP_RAID0        (1ull << 3)
#define EDGE_BTRFS_BLOCK_GROUP_RAID1        (1ull << 4)
#define EDGE_BTRFS_BLOCK_GROUP_DUP          (1ull << 5)
#define EDGE_BTRFS_BLOCK_GROUP_RAID10       (1ull << 6)
#define EDGE_BTRFS_BLOCK_GROUP_RAID5        (1ull << 7)
#define EDGE_BTRFS_BLOCK_GROUP_RAID6        (1ull << 8)
#define EDGE_BTRFS_BLOCK_GROUP_RAID1C3      (1ull << 9)
#define EDGE_BTRFS_BLOCK_GROUP_RAID1C4      (1ull << 10)
#define EDGE_BTRFS_UNSUPPORTED_PROFILES \
    (EDGE_BTRFS_BLOCK_GROUP_RAID0 | EDGE_BTRFS_BLOCK_GROUP_RAID10 | \
     EDGE_BTRFS_BLOCK_GROUP_RAID5 | EDGE_BTRFS_BLOCK_GROUP_RAID6)

#define EDGE_BTRFS_INCOMPAT_RAID56          (1ull << 7)
#define EDGE_BTRFS_INCOMPAT_ZONED           (1ull << 12)
#define EDGE_BTRFS_INCOMPAT_EXTENT_TREE_V2  (1ull << 13)
#define EDGE_BTRFS_UNSUPPORTED_INCOMPAT \
    (EDGE_BTRFS_INCOMPAT_RAID56 | EDGE_BTRFS_INCOMPAT_ZONED | \
     EDGE_BTRFS_INCOMPAT_EXTENT_TREE_V2)

#endif
